### ISSUE TITLE
Restarting partial downloads would be amazing

### ISSUE THREAD

**Issue by idiocracy2023** [elementdavv/internet_archive_downloader#18]
I'm trying to get a 700 page book and I can never get through more than 60% of the download before it fails.  Some way to pick back up where I left off would be incredible.  

Amazing tool regardless, thanks so much for making this.

**Comment by elementdavv** [comment]
Do you mean you have successfully download some books while it always fail with the 700 pages book?
Can you provide your os/browser versions, and the book link?

**Comment by idiocracy2023** [comment]
I just tried this 370pg one, 5 failures..
 https://archive.org/details/yogakarmarebirth0000phil/mode/2up

"TypeError: NetworkError when attempting to fetch resource..
Please contact the developer."

I am on a public library wifi connection in a small town (USA), really should be acceptable connection, but I can try a city library soon.

I just tried this 40 page book, five failures, maybe still a large file because its high resolution images
https://archive.org/details/troublefortrumpe00cros

Not sure how to find a small file size book to test, I keep clicking random books to look for a short page count with no luck.

**Comment by elementdavv** [comment]
When failed, press F12 to open developer page.
From 'Console' tab get a copy of the log message from 'Internet Archive Downloader 0.6.3 in action' line.

**Comment by idiocracy2023** [comment]
Thank you, this is what I found in the console

![Screenshot from 2023-09-19 15-38-40](https://github.com/elementdavv/internet_archive_downloader/assets/145053491/9e6c0fa8-9c74-4af4-a855-da7ee8a82f9b)

**Comment by elementdavv** [comment]
> Thank you, this is what I found in the console

It seems that the extension doesn't work in your firefox environment. It may be caused by ad blockers, other extensions or firewall settings.
Try using 'firefox -P' to create a new profile, and starting firefox with that profile, with all default settings and only this extension installed. And test again.

**Comment by logological** [comment]
Same problem here, using a fresh profile and no firewall.  Error and log messages are the same.

**Comment by elementdavv** [comment]
> Same problem here, using a fresh profile and no firewall. Error and log messages are the same.

Can you provide your os/browser and the error message details?

**Comment by logion2000** [comment]
It will be very useful if your browser extension can download a custom range of book pages. For example, if the download process gets broken due to unstable internet connection, we don't need to start over again. We can continue the download from where we left. This is especially helpful for large books (e.g., 1000 pages).

**Comment by elementdavv** [comment]
If the download fails because of network errors, you can click 'Download' button again, the download can continue from where it left.
